server:
    port: 8085
spring:
    profiles:
        active: dev
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        password: 1234Abc
        url: jdbc:postgresql://localhost:5432/huitzilopochtli_db
        username: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: false
        hibernate:
            ddl-auto: none
    sql:
        init:
            platform: postgres